version: '3'

services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: cmsato
            POSTGRES_PASSWORD: cmsato
            PGPASSWORD: cmsato
            POSTGRES_DB: sample
            TZ: 'Asia/Tokyo'
        ports:
            - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 81:80
        environment:
            PGADMIN_DEFAULT_EMAIL: briete5814@gmail.com
            PGADMIN_DEFAULT_PASSWORD: cmsato
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres
volumes:
    postgres:
    pgadmin:
